export const UPDATE_SLOT_REQUEST = "UPDATE_SLOT_REQUEST";
export const UPDATE_SLOT_SUCCESS = "UPDATE_SLOT_SUCCESS";
export const UPDATE_SLOT_RESET = "UPDATE_SLOT_RESET";
export const UPDATE_SLOT_FAIL = "UPDATE_SLOT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";